### ISSUE TITLE
[Enhancement] Hiding system

### ISSUE THREAD

**Issue by DawEdhel** [ghorint2t/scripts#6]
Huge sales arise a problem where you have to visually exclude titles you're not interested in to find something worthy.
To fix that I'm suggesting two non-exclusive solutions:

1. to hide temporarily, e.g. only for current page but to be persistent after various client actions like different filtering/sorting setups. That solution should help to hide games only for current sale, ones which could be interested in the future.
Setting and storing display:none might be enough. Reloading or new page should drop these hiding filters.

2. to hide permanently. That solution should help to hide never-interested-in titles, including such as already bought but not marked owned by GOG, duplicate entries, lesser than complete edition titles and etc.
Due to persistence requirement it has to be placed in the storage (along with setup values?), and as it can gain a lot of popularity to utilize, potentially there could be a need in extra functions:
    - to open separate permanently hidden titles' list, where you can unhide (or even better is to replace the main table with only hidden records).
    - to import/export storage values, including setup values, to make user's settings portable across browsers/PC.

In terms of interface placement for both solutions I'm suggesting adding two extra buttons for every table's entry to hide one by one.
Extra point is to implement new buttons (to the right side of "hide dlc" checkmark?) to hide all found multiple records by current filtering setup for various cases like specific title, genre, and so on.

For unhide permanent titles' mode reverse previous paragraph' buttons.

**Comment by ghorint2t** [comment]
Yes, I noticed some people asking about a 'blacklist' of games on the forums. Will think about it and maybe eventually add it (within the next month or so). Still, I think having two separate modes is too much clutter of the UI. If just the 'permanent' mode works with an easy option to unhide, that should be good enough.

**Comment by ghorint2t** [comment]
I've made the changes - apart from wishlist you can now blacklist a game (sadly will only work on the grid, not whole gog :)). As written previously, this is only the 'permanent' option, but should be good enough. To manage the list, I've added another tab (Blacklist) to the main display where the games can be un-blacklisted. Also added Wishlist tab for symmetry, should anyone want to eg. sort their wishlist by discount.

Since games can be added to the blacklist quickly enough, I don't think there's a need for the 'multiple entries' blacklist button; not a big timesaver, and can be problematic if someone accidentally clicks that with too big of a selection.

Save/load options are also available, for transferring between browsers and/or saving your favorite filter/sorting setups.

Leaving this issue open for now, should you or someone else find any bugs in current version.

**Comment by DawEdhel** [comment]
So far so good, but there are some nitpicks:
- There is a readme typo: "configuraration".
- It looks like blacklisting an entry removes it from wishlist/cart, which should be documented.
- New wishlist/blacklist tabs are located within gog space, which can make impression that these are part of site functionality, not a script one. The suggestion is to either move them to the script container, like between full page horizontal line separator and hide checks section, or mark differently with some style, or add a vertical line separator "|" in-between.

P.S. Also it looks like at the moment GOG broke something as cart/os svgs are not found to load, making an empty space. instead. Maybe there is a point to store these images separately to be independent on visual showcasing.

**Comment by ghorint2t** [comment]
#1,2: Readme fixed
#3: I like the tabs where they are, so I've just added a separator :)
#4: The icons work fine for me now. Must have been a temporary issue. I'd rather not make a copy; if gog updates the icons to a new version, I'll change the script to use new ones.
